# Generated by Django 4.1.7 on 2023-03-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour_spent', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                (
                    'project_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jappl_time_log.project'),
                ),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jappl_time_log.userdetail'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('project_member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_pm', models.BooleanField(default=False)),
                (
                    'project_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jappl_time_log.project'),
                ),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jappl_time_log.userdetail'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPermission',
            fields=[
                ('application_permission_id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'application_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jappl_time_log.application'),
                ),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jappl_time_log.userdetail'),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('user_id', 'project_id'), name='u_user_project'),
        ),
        migrations.AddConstraint(
            model_name='applicationpermission',
            constraint=models.UniqueConstraint(fields=('user_id', 'application_id'), name='u_user_application'),
        ),
    ]
