# Generated by Django 4.1.7 on 2023-03-02 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='hour_spent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
