# Generated by Django 4.1.7 on 2023-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0003_userdetail_is_super_admin_alter_userdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
