# Generated by Django 4.1.7 on 2023-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0004_alter_application_application_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationpermission',
            name='u_user_application',
        ),
        migrations.RenameField(
            model_name='applicationpermission',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='applicationpermission',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='applicationpermission',
            constraint=models.UniqueConstraint(fields=('user', 'application'), name='u_user_application'),
        ),
    ]
