# Generated by Django 4.1.7 on 2023-03-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0005_remove_applicationpermission_u_user_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='is_super_admin',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_role',
            field=models.CharField(
                choices=[('Employee', 'Employee'), ('Project Manager', 'Pm'), ('Admin', 'Admin')],
                default=None,
                help_text="User's role",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='applicationpermission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jappl_time_log.application'),
        ),
    ]
