# Generated by Django 4.1.7 on 2023-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0006_remove_userdetail_is_super_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_role',
            field=models.CharField(
                choices=[('User', 'User'), ('Employee', 'Employee'), ('Project Manager', 'Pm'), ('Admin', 'Admin')],
                default='User',
                help_text="User's role",
                max_length=100,
            ),
        ),
    ]
