# Generated by Django 4.1.7 on 2023-03-14 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0008_remove_userdetail_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
