# Generated by Django 4.1.7 on 2023-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jappl_time_log', '0010_remove_userdetail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
