
all: project timelog

project: sequential-diagram-project-flow.mmd
	mmdc -i  sequential-diagram-project-flow.mmd -o project-flow.png

timelog: sequential-diagram-timelog-flow.mmd
	mmdc -i  sequential-diagram-timelog-flow.mmd -o timelog-flow.png
