
sequenceDiagram
    autonumber
    actor User
    participant F as Frontend
    participant FA as Firebase Authentication
    participant BA as Backend API
    participant DB as Database
    User->>F: login with valid email
    activate F
    activate User
    F->>+FA: request for verification
    FA-->>-F: JWT token
    F->>BA: send request to /api/timelog/all with token from firebase
    activate BA
    alt when user login for the first time
        BA->>DB: insert new user
        activate DB
    end
    BA->>DB: query user information from user detail table
    DB-->>BA: user information
    BA->>DB: query time log
    DB-->>BA: list of time log
    deactivate DB
    BA-->>F: response with all time logs
    deactivate BA
    F-->>User: see dashboard


    User->>F: add/edit/delete timelog in dashboard page
    F->>BA: send request to api/timelog/add with token from firebase
    activate BA
    BA->>DB: query user information from user detail table
    activate DB
    DB-->>BA: user information
    alt when request is in invalid format for add and edit timelog
        BA-->>F: 400 bad request
        F-->>User: notification with error message
    end
    BA->>DB: insert/edit/delete timelog
    alt when can not find timelog
        DB-->>BA: integrity error
        BA-->>F: 404 not found
        F-->>User: notification with error message
    end
    DB-->>BA: added/updated/deleted timelog
    deactivate DB
    BA-->>F: response with added/updated/deleted timelog
    deactivate BA
    F-->>User: see updated timelog list
